### ISSUE TITLE
Y axis is actually around 133 long, not 140

### ISSUE THREAD

**Issue by mamoit** [BlocksTechnology/Blocks-zero#5]
It says everywhere that the axis is 140mm long, and all the configuration is set accordingly, but the axis is actually not that long, it is 133mm long (at least on the indiegogo version).
This causes the bed to ram into the acrylic case every time it tries to go to it's limits.
A safer option is to set the limits to 13cm, losing 1cm but ensuring that the virtual endstop of Y+ is not rammed into.

**Comment by choschiba** [comment]
I‘ve discovered the same thing actually too. And on the z axis I cannot go higher than about 110mm!
I have that Indigogo version. 
Is it possible to update the firmware to the newest version? Have you tried?

**Comment by mamoit** [comment]
Since posting this issue I actually got hired by Blocks, so now I have a better insight on this.
The problem is that the production version and the indiegogo version are physically different since the axis got a little bit longer in the latter.
This repository holds the code for the Production version of the Blocks Zero.

I have fixed this issue in [my version of Marlin](https://github.com/mamoit/Marlin/tree/bz-1.1.8) (which is just the up to date vanilla version tuned for the indiegogo version of the Blocks Zero), but it lacks some of the tweaks implemented in the Blocks code, such as the filament change routines.

Another option is to change the values for `Y_MAX_POS` and `Z_MAX_POS` in the [`Configuration.h`](https://github.com/BlocksTechnology/Blocks-zero/blob/master/Firmware_1.2/Marlin/Configuration.h#L345) and flash your printer with it, this way you can preserve the Blocks firmware features, and not have the printer hit the bed the limits.

Let me know if you need some help.
